### ISSUE TITLE
Add an example when __services: docker__ is added

### ISSUE THREAD

**Issue by cclauss** [deadsnakes/travis-ci-python3.7-example#5]
Many projects explicitly use __docker__ and it can be quite tricky to test them properly with parallel runs on both Python 2.7 and Python 3.7.
```
services:
  - docker
```
https://docs.travis-ci.com/user/docker/

**Comment by asottile** [comment]
I've done this before with `ARG` in docker: https://github.com/asottile/tox-virtualenv-no-download/blob/8b7662d66209c14b4cbc6f4f01d904b513be2413/.travis.yml

the tl;dr for using deadsnakes in docker is:

```dockerfile
ARG PYTHON=python2.7
RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends software-properties-common \
    && add-apt-repository -y ppa:deadsnakes \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends $PYTHON \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
```

And then some build commands like

```bash
docker build -t project-name-$PYTHON --build-arg PYTHON=$PYTHON .
```

And run commands like

```bash
docker run --rm project-name-$PYTHON ...
```
